version: '3'
services:
  weblate-database:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: weblate
      POSTGRES_USER: weblate
      POSTGRES_DATABASE: weblate
    volumes:
      - postgres-data:/var/lib/postgresql/data

  weblate-cache:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  weblate:
    image: weblate/weblate:latest
    depends_on:
      - weblate-database
      - weblate-cache
    environment:
      # Database
      POSTGRES_HOST: weblate-database
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: weblate
      POSTGRES_USER: weblate
      POSTGRES_PASSWORD: weblate
      # Redis
      REDIS_HOST: weblate-cache
      REDIS_PORT: 6379
      # Weblate
      WEBLATE_ADMIN_PASSWORD: admin123
      WEBLATE_ADMIN_NAME: admin
      WEBLATE_ADMIN_EMAIL: admin@example.com
      WEBLATE_SITE_TITLE: "Locale Test Weblate"
      WEBLATE_SITE_DOMAIN: "localhost:8080"
      WEBLATE_ALLOWED_HOSTS: "*"
      WEBLATE_DEBUG: "1"
    volumes:
      - weblate-data:/app/data
    ports:
      - "8080:8080"

volumes:
  postgres-data:
  redis-data:
  weblate-data:
